package com.pingfit.dao;

import com.pingfit.dao.hibernate.BasePersistentClass;
import com.pingfit.dao.hibernate.HibernateUtil;
import com.pingfit.session.AuthControlled;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:24 PM by Hibernate Tools 3.1.0.beta4


/**
 * Userrole generated by hbm2java
 */

public class Pladmin extends BasePersistentClass implements java.io.Serializable, AuthControlled {



    // Fields

     private int pladminid;
     private int userid;
     private int plid;





    public static Pladmin get(int id) {
        Logger logger = Logger.getLogger("com.pingfit.dao.Pladmin");
        try {
            logger.debug("Pladmin.get(" + id + ") called.");
            Pladmin obj = (Pladmin) HibernateUtil.getSession().get(Pladmin.class, id);
            if (obj == null) {
                logger.debug("Pladmin.get(" + id + ") returning new instance because hibernate returned null.");
                return new Pladmin();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.pingfit.dao.Pladmin", ex);
            return new Pladmin();
        }
    }

    // Constructors

    /** default constructor */
    public Pladmin() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }




    // Property accessors

    public int getPladminid() {
        return pladminid;
    }

    public void setPladminid(int pladminid) {
        this.pladminid=pladminid;
    }

    public int getUserid() {
        return userid;
    }

    public void setUserid(int userid) {
        this.userid=userid;
    }

    public int getPlid() {
        return plid;
    }

    public void setPlid(int plid) {
        this.plid=plid;
    }
}