package com.pingfit.dao;

import com.pingfit.dao.hibernate.BasePersistentClass;
import com.pingfit.dao.hibernate.HibernateUtil;
import com.pingfit.session.AuthControlled;
import org.apache.log4j.Logger;
// Generated Apr 17, 2006 3:45:24 PM by Hibernate Tools 3.1.0.beta4


/**
 * Userrole generated by hbm2java
 */

public class Plexerciselist extends BasePersistentClass implements java.io.Serializable, AuthControlled {



    // Fields

     private int plexerciselistid;
     private int plid;
     private int exerciselistid;




    public static Plexerciselist get(int id) {
        Logger logger = Logger.getLogger("com.pingfit.dao.Plexerciselist");
        try {
            logger.debug("Plexerciselist.get(" + id + ") called.");
            Plexerciselist obj = (Plexerciselist) HibernateUtil.getSession().get(Plexerciselist.class, id);
            if (obj == null) {
                logger.debug("Plexerciselist.get(" + id + ") returning new instance because hibernate returned null.");
                return new Plexerciselist();
            }
            return obj;
        } catch (Exception ex) {
            logger.error("com.pingfit.dao.Plexerciselist", ex);
            return new Plexerciselist();
        }
    }

    // Constructors

    /** default constructor */
    public Plexerciselist() {
    }

    public boolean canRead(User user){
        return true;
    }

    public boolean canEdit(User user){
        return canRead(user);
    }

    public Plexerciselist(int plexerciselistid, int plid, int exerciselistid) {
        this.plexerciselistid=plexerciselistid;
        this.plid=plid;
        this.exerciselistid=exerciselistid;
    }


    // Property accessors

    public int getPlexerciselistid() {
        return plexerciselistid;
    }

    public void setPlexerciselistid(int plexerciselistid) {
        this.plexerciselistid=plexerciselistid;
    }

    public int getPlid() {
        return plid;
    }

    public void setPlid(int plid) {
        this.plid=plid;
    }

    public int getExerciselistid() {
        return exerciselistid;
    }

    public void setExerciselistid(int exerciselistid) {
        this.exerciselistid=exerciselistid;
    }
}